version: 2
updates:
  # フロントエンド (Nuxt)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types:
          - "patch"

  # バックエンド (Lambda)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types:
          - "patch"

  # インフラ (CDK)
  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types:
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types:
          - "patch"
